name: Deploy Laravel Backend
on:
  push:
    branches:
      - main

jobs:
  sync-env:
    runs-on: ubuntu-latest
    steps:
      - name: Sync .env from Secrets
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Updating .env file on server..."
            cd /var/www/mld/mldbackend
            echo "${{ secrets.LARAVEL_ENV_FILE }}" > .env
            echo ".env updated."

  deploy:
    needs: sync-env
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Latest Code
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/mld/mldbackend
            git pull origin main
            docker compose up -d --build
            docker compose exec -T mldbackend php artisan migrate --force
            docker compose exec -T mldbackend php artisan optimize:clear
            docker compose exec -T mldbackend php artisan config:cache

  init:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Run Initialization Tasks
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/mld/mldbackend
            echo "Running initialization tasks..."
            docker compose exec -T mldbackend php artisan storage:link
            docker compose exec -T mldbackend php artisan optimize:clear
            echo "Initialization complete."
