name: Init Laravel Backend
on:
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Initial Setup on VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            PROJECT_PATH="/var/www/mld/mldbackend"
            if [ -d "$PROJECT_PATH" ]; then
              echo "Project already exists, aborting init."
              exit 1
            fi

            git clone -b main https://github.com/Ahmadfaisalkeren/mldbackend.git $PROJECT_PATH
            cd $PROJECT_PATH

            cp .env.example .env
            sed -i "s|APP_KEY=.*|APP_KEY=${{ secrets.APP_KEY }}|" .env
            sed -i "s|DB_HOST=.*|DB_HOST=global_mysql|" .env
            sed -i "s|DB_PASSWORD=.*|DB_PASSWORD=${{ secrets.DB_PASSWORD }}|" .env
            sed -i '/^DB_PASSWORD=/p; s/^DB_PASSWORD=/DB_ROOT_PASSWORD=/' .env
            sed -i "s|APP_DEBUG=.*|APP_DEBUG=false|" .env
            echo "${{ secrets.PUSHER }}" >> .env
            echo 'VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"' >> .env
            echo 'VITE_PUSHER_HOST="${PUSHER_HOST}"' >> .env
            echo 'VITE_PUSHER_PORT="${PUSHER_PORT}"' >> .env
            echo 'VITE_PUSHER_SCHEME="${PUSHER_SCHEME}"' >> .env
            echo 'VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"' >> .env

            docker compose up -d --build

            docker exec -i global_mysql mysql -u root -p${{ secrets.DB_PASSWORD }} \
              -e "CREATE DATABASE IF NOT EXISTS mldbackend;"

            docker compose exec -T mldbackend php artisan key:generate
            docker compose exec -T mldbackend php artisan migrate --force
            docker compose exec -T mldbackend php artisan storage:link
            docker compose exec -T mldbackend php artisan optimize:clear
            docker compose exec -T mldbackend php artisan config:cache
