name: Sync Laravel .env
on:
  workflow_dispatch:

jobs:
  sync-env:
    runs-on: ubuntu-latest
    steps:
      - name: Update Environment Variables
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/mld/mldbackend

            # Core app settings
            sed -i "s|^APP_KEY=.*|APP_KEY=${{ secrets.APP_KEY }}|" .env
            sed -i "s|^DB_PASSWORD=.*|DB_PASSWORD=${{ secrets.DB_PASSWORD }}|" .env
            sed -i '/^DB_PASSWORD=/p; s/^DB_PASSWORD=/DB_ROOT_PASSWORD=/' .env
            sed -i "s|^APP_DEBUG=.*|APP_DEBUG=false|" .env
            sed -i "s|^BROADCAST_CONNECTION=.*|BROADCAST_CONNECTION=pusher|" .env

            # Pusher settings (Laravel)
            sed -i "s|^PUSHER_APP_ID=.*|PUSHER_APP_ID=${{ secrets.PUSHER_APP_ID }}|" .env || echo "PUSHER_APP_ID=${{ secrets.PUSHER_APP_ID }}" >> .env
            sed -i "s|^PUSHER_APP_KEY=.*|PUSHER_APP_KEY=${{ secrets.PUSHER_APP_KEY }}|" .env || echo "PUSHER_APP_KEY=${{ secrets.PUSHER_APP_KEY }}" >> .env
            sed -i "s|^PUSHER_APP_SECRET=.*|PUSHER_APP_SECRET=${{ secrets.PUSHER_APP_SECRET }}|" .env || echo "PUSHER_APP_SECRET=${{ secrets.PUSHER_APP_SECRET }}" >> .env
            sed -i "s|^PUSHER_PORT=.*|PUSHER_PORT=${{ secrets.PUSHER_PORT }}|" .env || echo "PUSHER_PORT=${{ secrets.PUSHER_PORT }}" >> .env
            sed -i "s|^PUSHER_SCHEME=.*|PUSHER_SCHEME=${{ secrets.PUSHER_SCHEME }}|" .env || echo "PUSHER_SCHEME=${{ secrets.PUSHER_SCHEME }}" >> .env
            sed -i "s|^PUSHER_APP_CLUSTER=.*|PUSHER_APP_CLUSTER=${{ secrets.PUSHER_APP_CLUSTER }}|" .env || echo "PUSHER_APP_CLUSTER=${{ secrets.PUSHER_APP_CLUSTER }}" >> .env

            # Vite variables (frontend)
            sed -i "s|^VITE_PUSHER_APP_KEY=.*|VITE_PUSHER_APP_KEY=${{ secrets.PUSHER_APP_KEY }}|" .env || echo "VITE_PUSHER_APP_KEY=${{ secrets.PUSHER_APP_KEY }}" >> .env
            sed -i "s|^VITE_PUSHER_HOST=.*|VITE_PUSHER_HOST=${{ secrets.PUSHER_HOST }}|" .env || echo "VITE_PUSHER_HOST=${{ secrets.PUSHER_HOST }}" >> .env
            sed -i "s|^VITE_PUSHER_PORT=.*|VITE_PUSHER_PORT=${{ secrets.PUSHER_PORT }}|" .env || echo "VITE_PUSHER_PORT=${{ secrets.PUSHER_PORT }}" >> .env
            sed -i "s|^VITE_PUSHER_SCHEME=.*|VITE_PUSHER_SCHEME=${{ secrets.PUSHER_SCHEME }}|" .env || echo "VITE_PUSHER_SCHEME=${{ secrets.PUSHER_SCHEME }}" >> .env
            sed -i "s|^VITE_PUSHER_APP_CLUSTER=.*|VITE_PUSHER_APP_CLUSTER=${{ secrets.PUSHER_APP_CLUSTER }}|" .env || echo "VITE_PUSHER_APP_CLUSTER=${{ secrets.PUSHER_APP_CLUSTER }}" >> .env

            # Restart backend container
            docker compose restart mldbackend
